// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NWO.Server.Data;

#nullable disable

namespace NWO.Server.Data.Migrations
{
    [DbContext(typeof(GameDb))]
    [Migration("20261001231915_Research")]
    partial class Research
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("NWO.Server.Data.Ballot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElectionNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NationId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VoterId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NationId", "ElectionNo", "VoterId")
                        .IsUnique();

                    b.ToTable("Ballots");
                });

            modelBuilder.Entity("NWO.Server.Data.Camp", b =>
                {
                    b.Property<int>("Sector")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClearedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClearedUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("Sector");

                    b.ToTable("Camps");
                });

            modelBuilder.Entity("NWO.Server.Data.Candidate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElectionNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NationId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Speech")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SpeechAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NationId", "ElectionNo", "PlayerId")
                        .IsUnique();

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("NWO.Server.Data.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("At")
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Channel", "Id");

                    b.ToTable("Chat");
                });

            modelBuilder.Entity("NWO.Server.Data.Contract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Qty")
                        .HasColumnType("REAL");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Reward")
                        .HasColumnType("REAL");

                    b.Property<int>("Sector")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TakenById")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("NWO.Server.Data.Coup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Backers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LeaderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Needed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coups");
                });

            modelBuilder.Entity("NWO.Server.Data.Drone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DownUntil")
                        .HasColumnType("TEXT");

                    b.Property<int>("Idx")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sector")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Sector", "Idx")
                        .IsUnique();

                    b.ToTable("Drones");
                });

            modelBuilder.Entity("NWO.Server.Data.HomeTile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Rotated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("HomeTiles");
                });

            modelBuilder.Entity("NWO.Server.Data.Law", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Against")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("For")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProposedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("NationId", "Status");

                    b.ToTable("Laws");
                });

            modelBuilder.Entity("NWO.Server.Data.LawVote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("For")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LawId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VoterId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LawId", "VoterId")
                        .IsUnique();

                    b.ToTable("LawVotes");
                });

            modelBuilder.Entity("NWO.Server.Data.LedgerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("At")
                        .HasColumnType("TEXT");

                    b.Property<double>("Balance")
                        .HasColumnType("REAL");

                    b.Property<double>("Delta")
                        .HasColumnType("REAL");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Id");

                    b.ToTable("Ledger");
                });

            modelBuilder.Entity("NWO.Server.Data.Nation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ElectionAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ElectionNo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("FounderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Government")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSpeechAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Legitimacy")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MarketTax")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PresidentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PresidentName")
                        .HasColumnType("TEXT");

                    b.Property<double>("SmuggleFine")
                        .HasColumnType("REAL");

                    b.Property<double>("TaxRate")
                        .HasColumnType("REAL");

                    b.Property<double>("Treasury")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Nations");
                });

            modelBuilder.Entity("NWO.Server.Data.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<double>("Qty")
                        .HasColumnType("REAL");

                    b.Property<double>("Remaining")
                        .HasColumnType("REAL");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Resource", "Side", "Price");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("NWO.Server.Data.Parcel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Buildings")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("I")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHome")
                        .HasColumnType("INTEGER");

                    b.Property<int>("J")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sector")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Sector", "I", "J")
                        .IsUnique();

                    b.ToTable("Parcels");
                });

            modelBuilder.Entity("NWO.Server.Data.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CampAssaultAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CampAssaultSector")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Captures")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cash")
                        .HasColumnType("REAL");

                    b.Property<int>("Catches")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DroneHuntAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DroneHuntIdx")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DroneHuntSector")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Fuel")
                        .HasColumnType("REAL");

                    b.Property<double>("Gold")
                        .HasColumnType("REAL");

                    b.Property<double>("Grain")
                        .HasColumnType("REAL");

                    b.Property<string>("HomeBuildings")
                        .HasColumnType("TEXT");

                    b.Property<int>("HomeLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeSector")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HqLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("InspectDay")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InspectFadeAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InspectStreak")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InspectsToday")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastCampClearAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastCollectAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastRationAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Misses")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NationChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Oil")
                        .HasColumnType("REAL");

                    b.Property<double>("Power")
                        .HasColumnType("REAL");

                    b.Property<string>("RecoveryHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResearchEndsAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResearchId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Standing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Techs")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TutorialStep")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WarScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("NWO.Server.Data.RecordEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("At")
                        .HasColumnType("TEXT");

                    b.Property<int>("Delta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Id");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("NWO.Server.Data.ServerState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gatebreakers")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Region2Open")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Region2OpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SentinelAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SentinelNextAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Server");
                });

            modelBuilder.Entity("NWO.Server.Data.Shipment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ArriveAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AuditAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuditPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Checked")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DepartAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Envelope")
                        .HasColumnType("REAL");

                    b.Property<int>("From")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("HeldById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HeldUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Legal")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Qty")
                        .HasColumnType("REAL");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Reward")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StopResolveAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoppedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("To")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("NWO.Server.Data.Trade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("At")
                        .HasColumnType("TEXT");

                    b.Property<string>("Buyer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<double>("Qty")
                        .HasColumnType("REAL");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Seller")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Resource", "Id");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("NWO.Server.Data.War", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("A")
                        .HasColumnType("INTEGER");

                    b.Property<int>("B")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PeaceOfferedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Wars");
                });

            modelBuilder.Entity("NWO.Server.Data.HomeTile", b =>
                {
                    b.HasOne("NWO.Server.Data.Player", null)
                        .WithMany("HomeTiles")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NWO.Server.Data.Order", b =>
                {
                    b.HasOne("NWO.Server.Data.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NWO.Server.Data.Parcel", b =>
                {
                    b.HasOne("NWO.Server.Data.Player", "Owner")
                        .WithMany("Parcels")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("NWO.Server.Data.Player", b =>
                {
                    b.Navigation("HomeTiles");

                    b.Navigation("Parcels");
                });
#pragma warning restore 612, 618
        }
    }
}
